name: Alerta Push a Main

on:
  push:
    branches:
      - main

jobs:
  notificacion:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener cÃ³digo del repositorio
        uses: actions/checkout@v4

      - name: Enviar notificaciÃ³n a ntfy
        run: |
          curl -X POST https://ntfy.sh/devops-itla \
          -H "Title: Nuevos cambios en main ðŸš¨" \
          -H "Priority: 4" \
          -H "Tags: github,ci-cd,alerta" \
          -d "Repositorio: ${{ github.repository }}
          Usuario: ${{ github.actor }}
          Commit: ${{ github.event.head_commit.message }}
          Hora: $(date)"
